# Generated by Django 4.1.3 on 2022-11-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review_review_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_username',
            new_name='review_user',
        ),
    ]
